- job_name: 'node_exporter'
  metrics_path: /metrics
  static_configs:
    - targets: ['ec2-3-22-60-224.us-east-2.compute.amazonaws.com:9100']

- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://3.22.60.224/events # udacity
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115
